package generators

import (
	"amphion-tools/project"
	"os"
	"path/filepath"
	"text/template"
)

const mainAndroidFileTemplate = `
package main

// This file is automatically generated
// DO NOT EDIT THIS FILE MANUALLY!!!

func runApp() {
	
}
`

var androidTemplate = `
//+build android

package droidCli

// This file is automatically generated
// DO NOT EDIT THIS FILE MANUALLY!!!

import (
	"github.com/cadmean-ru/amphion/engine"
	"github.com/cadmean-ru/amphion/frontend"
	"github.com/cadmean-ru/amphion/frontend/android"
	"github.com/cadmean-ru/amphion/frontend/cli"
	{{ range $imp := .CompData.Imports }}
	"{{ $imp }}"
	{{ end }}
)

var front frontend.Frontend

func AmphionInitAndroid(f cli.FrontendDelegate, rm cli.ResourceManagerDelegate, rd cli.RendererDelegate) {
	front = android.NewFrontend(f, rm, rd)
	front.Init()

	e := engine.Initialize(front)
	
	cm := e.GetComponentsManager()
	
	{{ range $comp := .CompData.Components }}
	cm.RegisterComponentType(&{{ $comp.LastPackage }}.{{ $comp.Name }}{})
	{{ end }}
	
	{{ if (gt (len .Resources) 0) }}
	rm1 := e.GetResourceManager()
		{{ range $res := .Resources }}
	rm1.RegisterResource("{{ $res }}")
		{{ end }}
	{{ end }}

	go func() {
		e.Start()
		e.LoadApp(&AppDelegate{})
	}()

	go front.Run()
}

func RegisterPrimitiveRendererDelegate(primitiveKind int, delegate cli.PrimitiveRendererDelegate) {
	front.GetRenderer().RegisterPrimitiveRendererDelegate(byte(primitiveKind), cli.NewPrimitiveRendererDelegateWrap(delegate))
}

func GetRenderingPerformer() *cli.ExecDelegate {
	return cli.NewExecDelegate(front.GetRenderer().GetRenderingPerformer())
}

func GetRendererPrepareDelegate() *cli.ExecDelegate {
	return cli.NewExecDelegate(front.GetRenderer().Prepare)
}
`

func AndroidMain(data *MainTemplateData, projPath string, config *project.Config, runConfig *project.RunConfig) error {
	return generateMainFile(data, mainAndroidFileTemplate, projPath, config, runConfig)
}

func Android(data *MainTemplateData, projPath string, config *project.Config, runConfig *project.RunConfig) (err error) {
	codePath := filepath.Join(projPath, config.Name)
	androidPath := filepath.Join(codePath, "generated", "droidCli")

	mainTmpl := template.Must(template.New("main").Parse(androidTemplate))

	os.MkdirAll(androidPath, os.FileMode(0777))

	mainFile, err := os.Create(filepath.Join(androidPath, "android.gen.go"))
	if err != nil {
		return
	}
	defer mainFile.Close()

	err = mainTmpl.Execute(mainFile, *data)
	return
}